### ISSUE TITLE
Update to latest version of Cesium

### ISSUE THREAD

**Issue by laurensdijkstra** [DigitalArsenal/webpack-cesium#1]
Hi it would be nice if you could update to the latest version of Cesium at the moment of writing this (1.35). Perhaps an automated solution is an option where you build a new release every time Cesium releases a new version.

**Comment by TJKoury** [comment]
@laurensdijkstra Will do, just testing out the latest version to make sure everything works ok.

**Comment by TJKoury** [comment]
Done!
