### ISSUE TITLE
New version of Cesium 1.39

### ISSUE THREAD

**Issue by cramatt** [DigitalArsenal/webpack-cesium#2]
Supports webpack natively, but still with a lot of config. Would be nice to have a one stop module.

**Comment by TJKoury** [comment]
That's what we're going for here!  ...or did you mean this version needs a lot of config as well?

**Comment by cramatt** [comment]
Sorry, to clarify Cesium 1.39 is out and although it supports webpack natively, this still requires a bit of config to get working. 

It would still be worth updating this module to use 1.39 however, to get the "no config necessary" usage and also to support the other new features of this release.

**Comment by TJKoury** [comment]
Still working on a build process to support automated builds, will have it done some time this summer.
