### ISSUE TITLE
Does not work with example provided

### ISSUE THREAD

**Issue by cramatt** [DigitalArsenal/webpack-cesium#3]
The following is resulting in undefined for me. 

```
const Cesium = require('webpack-cesium');
console.log('Cesium', Cesium); //=> undefined
```

Any suggestions? What info would be useful to provide in addition to the above snippet?

**Comment by TJKoury** [comment]
What is your build environment?

**Comment by cramatt** [comment]
React storybook using webpack 2. 

Mac OS 10.12.3. 

Node v7.8.0, NPM 4.2.0

**Comment by TJKoury** [comment]
If you drop to Node REPL in the  root directory and `require('webpack-cesium')`, what happens?

**Comment by cramatt** [comment]
Node REPL works as expected and prints: 

```
require('webpack-cesium').VERSION
=> '1.37'
```

So maybe webpack -> storybook is scrambling things...

**Comment by TJKoury** [comment]
Are you using Babel?  ES5 or ES6, combined require/import?

**Comment by TJKoury** [comment]
Can you try and see if window.Cesium exists after import?

**Comment by cramatt** [comment]
Babel yes, es6 imports mostly and some requires. 

Seems to be defined in the iframe in which storybook bootstraps your components. in the main window it's not defined.

**Comment by TJKoury** [comment]
Closing this, will open if more info is provided.
